#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Append part2 to run_efficiency_frontier.py"""
import ast
from pathlib import Path

part2 = (
    "\n\ndef run_pipeline(\n"
    "    strategy, target_budget, all_results,\n"
    "    router, backfill_controller, prompter, agent_b_callable,\n"
    "):\n"
    "    N = len(all_results)\n"
    "    if N == 0:\n"
    "        return None\n"
    "    n_call_target = int(round(N * target_budget))\n"
    "\n"
    "    if strategy == 'AgentA_Only':\n"
    "        cer_num = sum(Levenshtein.distance(r['T_A'], r['T_GT']) for r in all_results)\n"
    "        gt_len = sum(len(r['T_GT']) for r in all_results)\n"
    "        return {\n"
    "            'Strategy': 'AgentA_Only', 'Target_Budget': 0.0,\n"
    "            'Actual_Call_Rate': 0.0,\n"
    "            'Overall_CER': round(cer_num / gt_len, 6) if gt_len else 0,\n"
    "            'AER': 0.0, 'CVR': 0.0, 'N_valid': N,\n"
    "        }\n"
    "\n"
    "    if strategy == 'Random':\n"
    "        scores = [random.random() for _ in range(N)]\n"
    "    elif strategy == 'ConfOnly':\n"
    "        scores = [(1.0 - r['mean_conf']) + (1.0 - r['min_conf']) + r['drop']\n"
    "                  for r in all_results]\n"
    "    else:\n"
    "        scores = []\n"
    "        for r in all_results:\n"
    "            dec = router.route(\n"
    "                boundary_stats=r['boundary_stats'],\n"
    "                top2_info=r['top2_info'],\n"
    "                r_d=r['r_d'],\n"
    "                agent_a_text=r['T_A'],\n"
    "            )\n"
    "            scores.append(dec.q)\n"
    "\n"
    "    upgrade_set = set(\n"
    "        sorted(range(N), key=lambda i: scores[i], reverse=True)[:n_call_target]\n"
    "    )\n"
    "    cer_num = 0\n"
    "    gt_len = 0\n"
    "    n_upgraded = 0\n"
    "    n_accepted_edit = 0\n"
    "    n_rejected = 0\n"
    "    from modules.router.backfill import RouteType\n"
    "    for i, r in enumerate(tqdm(all_results, desc=f'{strategy} B={target_budget:.2f}', leave=False)):\n"
    "        T_A = r['T_A']\n"
    "        T_GT = r['T_GT']\n"
    "        if i in upgrade_set:\n"
    "            n_upgraded += 1\n"
    "            prompt = prompter.generate_targeted_correction_prompt(\n"
    "                T_A=T_A, min_conf_idx=r['min_conf_idx'],\n"
    "                domain='\u5730\u8d28\u52d8\u63a2', image_path=r['img_path'],\n"
    "            )\n"
    "            prompt['T_A'] = T_A\n"
    "            T_cand = agent_b_callable(prompt)\n"
    "            bf = backfill_controller.apply_backfill(\n"
    "                T_A=T_A, T_cand=T_cand, route_type=RouteType.BOUNDARY,\n"
    "            )\n"
    "            T_final = bf.T_final\n"
    "            if bf.is_rejected:\n"
    "                n_rejected += 1\n"
    "            elif T_final != T_A:\n"
    "                n_accepted_edit += 1\n"
    "        else:\n"
    "            T_final = T_A\n"
    "        cer_num += Levenshtein.distance(T_final, T_GT)\n"
    "        gt_len += len(T_GT)\n"
    "\n"
    "    actual_rate = n_upgraded / N if N > 0 else 0.0\n"
    "    overall_cer = cer_num / gt_len if gt_len > 0 else 0.0\n"
    "    aer = n_accepted_edit / n_upgraded if n_upgraded > 0 else 0.0\n"
    "    cvr = n_rejected / n_upgraded if n_upgraded > 0 else 0.0\n"
    "    return {\n"
    "        'Strategy': strategy, 'Target_Budget': target_budget,\n"
    "        'Actual_Call_Rate': round(actual_rate, 4),\n"
    "        'Overall_CER': round(overall_cer, 6),\n"
    "        'AER': round(aer, 4), 'CVR': round(cvr, 4), 'N_valid': N,\n"
    "    }\n"
    "\n"
    "\ndef main():\n"
    "    parser = argparse.ArgumentParser(description='SH-DA++ v5.1 Phase 3')\n"
    "    parser.add_argument('--config', default='configs/router_config.yaml')\n"
    "    parser.add_argument('--test_jsonl', default='data/raw/hctr_riskbench/test.jsonl')\n"
    "    parser.add_argument('--image_root', default='data/geo')\n"
    "    parser.add_argument('--rec_model_dir', default='./models/agent_a_ppocr/PP-OCRv5_server_rec_infer')\n"
    "    parser.add_argument('--rec_char_dict_path', default='ppocr/utils/ppocrv5_dict.txt')\n"
    "    parser.add_argument('--geo_dict', default='data/dicts/Geology.txt')\n"
    "    parser.add_argument('--output_dir', default='results/stage2_v51')\n"
    "    parser.add_argument('--budgets', default='0.05,0.10,0.20,0.30')\n"
    "    parser.add_argument('--seed', type=int, default=42)\n"
    "    args = parser.parse_args()\n"
    "    random.seed(args.seed)\n"
    "    np.random.seed(args.seed)\n"
    "    with open(args.config, 'r', encoding='utf-8') as f:\n"
    "        config = yaml.safe_load(f)\n"
    "    print('[1/4] Init Agent A...')\n"
    "    import argparse as _ap\n"
    "    rec_args = _ap.Namespace(\n"
    "        rec_model_dir=args.rec_model_dir,\n"
    "        rec_char_dict_path=args.rec_char_dict_path,\n"
    "        rec_image_shape='3, 48, 320', rec_batch_num=6,\n"
    "        rec_algorithm='SVTR_LCNet', use_space_char=True,\n"
    "        use_gpu=True, use_xpu=False, use_npu=False, use_mlu=False,\n"
    "        use_metax_gpu=False, use_gcu=False, ir_optim=True,\n"
    "        use_tensorrt=False, min_subgraph_size=15, precision='fp32',\n"
    "        gpu_mem=500, gpu_id=0, enable_mkldnn=None, cpu_threads=10,\n"
    "        warmup=False, benchmark=False, save_log_path='./log_output/',\n"
    "        show_log=False, use_onnx=False, max_batch_size=10,\n"
    "        return_word_box=False, drop_score=0.5, max_text_length=25,\n"
    "        rec_image_inverse=True, use_det=False, det_model_dir='',\n"
    "    )\n"
    "    from modules.paddle_engine.predict_rec_modified import TextRecognizerWithLogits\n"
    "    recognizer = TextRecognizerWithLogits(rec_args)\n"
    "    print('[2/4] Init Router and components...')\n"
    "    from modules.router.sh_da_router import SHDARouter\n"
    "    from modules.router.backfill import BackfillConfig, StrictBackfillController\n"
    "    from modules.vlm_expert.constrained_prompter import ConstrainedPrompter\n"
    "    from modules.router.domain_knowledge import DomainKnowledgeEngine\n"
    "    router = SHDARouter.from_yaml(args.config)\n"
    "    backfill_controller = StrictBackfillController(BackfillConfig())\n"
    "    prompter = ConstrainedPrompter()\n"
    "    domain_engine = DomainKnowledgeEngine(args.geo_dict)\n"
    "    agent_b_callable = build_agent_b_callable(config)\n"
    "    print('[3/4] Load test set...')\n"
    "    samples = []\n"
    "    with open(args.test_jsonl, 'r', encoding='utf-8') as f:\n"
    "        for line in f:\n"
    "            line = line.strip()\n"
    "            if line:\n"
    "                samples.append(json.loads(line))\n"
    "    print(f'  Test: {len(samples)} samples')\n"
    "    print('[4/4] Agent A full inference...')\n"
    "    all_results = infer_all_samples(samples, recognizer, domain_engine, None, args.image_root)\n"
    "    print(f'  Valid: {len(all_results)}')\n"
    "    output_dir = Path(args.output_dir)\n"
    "    output_dir.mkdir(parents=True, exist_ok=True)\n"
    "    csv_path = output_dir / 'efficiency_frontier.csv'\n"
    "    fieldnames = ['Strategy', 'Target_Budget', 'Actual_Call_Rate',\n"
    "                  'Overall_CER', 'AER', 'CVR', 'N_valid']\n"
    "    with open(csv_path, 'w', newline='', encoding='utf-8') as csvfile:\n"
    "        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)\n"
    "        writer.writeheader()\n"
    "        budgets = [float(b) for b in args.budgets.split(',')]\n"
    "        print('\\n--- AgentA_Only (Baseline 0) ---')\n"
    "        row = run_pipeline('AgentA_Only', 0.0, all_results, router,\n"
    "                           backfill_controller, prompter, agent_b_callable)\n"
    "        writer.writerow({k: row.get(k, '') for k in fieldnames})\n"
    "        csvfile.flush()\n"
    "        print(f\"  CER={row['Overall_CER']:.4%}\")\n"
    "        for B in budgets:\n"
    "            for strategy in ['Random', 'ConfOnly', 'SH-DA++']:\n"
    "                print(f'\\n--- {strategy} B={B:.2f} ---')\n"
    "                row = run_pipeline(strategy, B, all_results, router,\n"
    "                                   backfill_controller, prompter, agent_b_callable)\n"
    "                writer.writerow({k: row.get(k, '') for k in fieldnames})\n"
    "                csvfile.flush()\n"
    "                print(\n"
    "                    f\"  CER={row['Overall_CER']:.4%}\"\n"
    "                    f\"  AER={row['AER']:.2%}\"\n"
    "                    f\"  CVR={row['CVR']:.2%}\"\n"
    "                    f\"  ActualRate={row['Actual_Call_Rate']:.2%}\"\n"
    "                )\n"
    "    print(f'\\nDone: {csv_path}')\n"
    "\n"
    "\nif __name__ == '__main__':\n"
    "    main()\n"
)

path = Path('scripts/run_efficiency_frontier.py')
current = path.read_text(encoding='utf-8')
if 'def run_pipeline' in current:
    current = current[:current.index('def run_pipeline')]
final = current + part2
path.write_text(final, encoding='utf-8')
try:
    ast.parse(final)
    print('Syntax OK,', len(final.splitlines()), 'lines')
except SyntaxError as e:
    ctx = final.splitlines()
    print(f'ERROR line {e.lineno}: {e.msg}')
    for i in range(max(0, e.lineno-2), min(len(ctx), e.lineno+1)):
        print(f'  {i+1}: {repr(ctx[i])}')
